/*
 * This header is generated by classdump-dyld 0.1
 * on Wednesday, September 20, 2017 at 9:27:39 PM Eastern European Summer Time
 * Operating System: Version 11.0 (Build 15A372)
 * Image Source: /System/Library/Frameworks/UIKit.framework/UIKit
 * classdump-dyld is free of use, Copyright © 2013 by Elias Limneos.
 */

// As credit above, header dumped using Elias Limneos' classdump-dyld
// Types cleaned up by ipad_kid
// Using iOS 11 header, becuase that's the SDK used to compile

@interface _UIAssetManager : NSObject

@property (nonatomic, readonly) NSString *carFileName;
@property (nonatomic, readonly) NSBundle *bundle;

+ (instancetype)assetManagerForBundle:(NSBundle *)bundle;
- (instancetype)initWithName:(NSString *)name inBundle:(NSBundle *)bundle idiom:(UIUserInterfaceIdiom)idiom;
- (UIImage *)imageNamed:(NSString *)imageName;
- (UIImage *)imageNamed:(NSString *)imageName idiom:(UIUserInterfaceIdiom)idiom;
@end
